force-app/main/default/objects/Cricketer__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <defaultValue>&quot;https://png.pngtree.com/png-clipart/20210129/ourmid/pngtree-blue-default-avatar-png-image_2813123.jpg&quot;</defaultValue>
    <label>Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Cricketer__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bowler</fullName>
            </value>
            <value>
                <fullName>All-rounder</fullName>
            </value>
            <value>
                <fullName>Batter</fullName>
            </value>
            <value>
                <fullName>Wicket-keeper</fullName>
            </value>
            <value>
                <fullName>Captain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cricketer__c/fields/Teams__c.field-meta.xml
<CustomField>
    <fullName>Teams__c</fullName>
    <label>Teams</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>RCB</fullName>
            </value>
            <value>
                <fullName>CSK</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>PBKS</fullName>
            </value>
            <value>
                <fullName>KKR</fullName>
            </value>
            <value>
                <fullName>GT</fullName>
            </value>
            <value>
                <fullName>SRH</fullName>
            </value>
            <value>
                <fullName>LSG</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/getCricketerList.cls
public with sharing class getCricketerList {
    @AuraEnabled(cacheable=true)
    public static List<Cricketer__c> getCricketerList(String selectedTeam) {
          
        if(selectedTeam == ''){
            List<Cricketer__c> playersData = [Select Id, Name, Teams__c,Specialization__c,Price__c,Image__c from Cricketer__c];
            return playersData;
        }
    else{ 
            
            List<Cricketer__c> playersData = [Select Id, Name, Teams__c,Specialization__c,Price__c,Image__c from Cricketer__c where Teams__c = : selectedTeam];
            return playersData;
        }
       
    } 

    

    @AuraEnabled(cacheable=true)
    public static Cricketer__c getSelectedPlayerData(String sendDataId) {
          
       
            Cricketer__c playersData = [Select Id, Name, Teams__c,Specialization__c,Price__c,Image__c from Cricketer__c where Id =: sendDataId];
            System.debug(playersData);
            return playersData;
        
    
       
    } 
}